name: My First Automation

on:
  push:
    branches: [main]
  workflow_dispatch:
    inputs:
      customer:
        description: 'What is the customer ?'
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Matrix Example
        run: |
          echo "terraform plan -var-file environments/${{ github.events.inputs.customer }}/variables.tfvars"
          echo "3rd line"
