name: My First Automation

on:
  # push:
  #   branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]

  on:
    workflow_dispatch:
      inputs:
        tags:
          description: 'Test scenario tags'
          required: true
          type: string

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run a one-line script
        run: echo this is my first input ${{ inputs.tags }}

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
          echo ${{ secrets.MY_FIRST_SECRET }}
