name: My First Automation

on:
  push:
    branches: [main]
  workflow_dispatch:
    inputs:
      customer:
        description: 'What is the customer ?'
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        customers: [fred, barney, wilma, bambam ]
    steps:
      - uses: actions/checkout@v3

      - name: Matrix Example
        run: echo "this is for ${{ matrix.customers }}"

