name: My First Automation

on:
  # push:
  #   branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]
  workflow_dispatch:
    inputs:
      customer:
        description: 'What is the customer ?'
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run a one-line script
        run: echo this is for barney
        if: inputs.customer == 'barney'

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
          echo ${{ secrets.MY_FIRST_SECRET }}
        if: inputs.customer != 'barney'  
