name: My First Automation

on:
  workflow_dispatch:
  push:
    branches: [main]
    inputs:
      customer:
        description: 'What is the customer ?'
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      build_id: ${{ steps.build_step.outputs.build_id }}

    steps:
      - uses: actions/checkout@v3

      - name: Run a one-line script
        run: echo "build_id=$BUILD_ID" >> $GITHUB_OUTPUT

      - name: Run a multi-line script
        run: |
          echo this is the build id ${{ steps.build_step.outputs.build_id }}
